Repository befreestudios-io/web-components-sandbox, pull requests merged in 2022-10, with the labels that each got.

#13 First pass at lit components
  .gitignore
  components/LIT/MyElement.html
  components/LIT/MyElement.js
  jsconfig.json
  package-lock.json
  package.json
Labels: hacktoberfest, hacktoberfest-accepted

#21 Resolves #20
  src/components/HelloWorld/HelloWorld.js
  src/components/HelloWorld/ShadowRootExample.js
  src/components/HelloWorld/Template.js
  src/components/HelloWorld/index.html
  src/components/LIT/MyElement.html
  src/components/LIT/MyElement.js
  src/components/Modal/index.html
  src/components/Modal/modal.css
  src/components/Modal/modal.js
  src/components/Modal/modal.template.html
  src/index.html
  src/templating/book-example/books.css
  src/templating/book-example/books.js
  src/templating/book-example/index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#22 lit carousel
  .eslintignore
  .eslintrc.json
  .gitignore
  components/LIT/dev/demo1.html
  components/LIT/dev/demo2.html
  components/LIT/dev/demo3.html
  components/LIT/dev/index.html
  components/LIT/lib/constants.js
  components/LIT/lib/simple-carousal.js
  components/LIT/lib/slide-button.js
  components/LIT/src/constants.js
  components/LIT/src/simple-carousal.ts
  components/LIT/src/slide-button.ts
  index.html
  tsconfig.json
  web-dev-server.config.js
Labels: hacktoberfest-accepted

#25 Resolves #24 - moves components to sandbox
  src/components/LIT/MyElement.js
  src/components/__SANDBOX__/HelloWorld/HelloWorld.js
  src/components/__SANDBOX__/HelloWorld/ShadowRootExample.js
  src/components/__SANDBOX__/HelloWorld/Template.js
  src/components/__SANDBOX__/HelloWorld/index.html
  src/components/__SANDBOX__/LIT/MyElement.html
  src/components/__SANDBOX__/LIT/MyElement.ts
Labels: hacktoberfest, hacktoberfest-accepted
